# Generated by Django 3.2.18 on 2023-04-11 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_comment_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comments',
        ),
    ]
