# Generated by Django 3.2.18 on 2023-03-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_category_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default=7, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
