# Generated by Django 3.2.18 on 2023-03-16 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_alter_category_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_category',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
