# Generated by Django 3.2.18 on 2023-03-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_alter_category_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='post',
            field=models.TextField(),
        ),
    ]
