# Generated by Django 3.2.18 on 2023-03-16 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0022_auto_20230316_1607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='post_category',
            new_name='category',
        ),
    ]
