# Generated by Django 3.2.18 on 2023-04-03 21:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0032_auto_20230402_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comments',
        ),
        migrations.AddField(
            model_name='post',
            name='unlikes',
            field=models.ManyToManyField(blank=True, related_name='news_unlikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
