# Generated by Django 3.2.18 on 2023-04-03 21:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0033_auto_20230403_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='post_comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
