# Generated by Django 3.2.18 on 2023-04-03 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0035_auto_20230403_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comments',
        ),
    ]
